check shasum of go download before using it

diff --git a/customize b/customize
--- a/customize
+++ b/customize
@@ -9,8 +9,11 @@ export LANGUAGE=en_US.utf8
 export LANG=en_US.utf8
 
 DENDRITE_VERSION="0.13.6"
-GO_VERSION="1.21.7"
 PGSQL_VERSION="16"
+
+# Get shasums from: https://go.dev/dl/
+GO_VERSION="1.21.7"
+GO_SHASUM="13b76a9b2a26823e53062fa841b07087d48ae2ef2936445dc34c4ae03293702c"
 
 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 
@@ -37,8 +40,14 @@ echo "* Install postgres"
 apt-get update
 apt-get install -y postgresql postgresql-contrib
 
+echo "* Fetch go"
+curl -LOs https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz
+if ! echo -n "${GO_SHASUM}  ./go${GO_VERSION}.linux-amd64.tar.gz" | shasum --check -a 256 -; then
+  echo "* ERROR: exiting, wrong shasum of go file"
+  exit 1
+fi
+
 echo "* Install go"
-curl -LO https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz
 tar -C /usr/local -xvf go${GO_VERSION}.linux-amd64.tar.gz
 export PATH=$PATH:/usr/local/go/bin
 
